languange: cpp
compiler :
- g++
install:
- sudo pip install codecov
os:
- linux
script:
- make -C make
- make/triangle_unittest
- make/nextdate_unittest
- make/commission_unittest
branches:
 only:
 - master
after_success:
  - codecov -X gcov
