languange: cpp
compiler :
- g++
install:
- sudo pip install codecov
os:
- linux
script:
- make -C make
- make/triangle_unittest
- make/nextdate_unittest
- make/commission_unittest
branches:
 only:
 - master
after_success:
  - codecov -t 3686bf12-4804-4ed5-a1d6-6a0801e2847d -X gcov
